### ISSUE TITLE
Moving this into the FineUploader GitHub org

### ISSUE THREAD

**Issue by rnicholus** [orlandovald/fineuploader-go-server#1]
Would you be interested in transferring this to the FineUploader org? Of course I would set you as a collaborator for this repo in the org. There we could talk about any changes that would be prudent to make this a generic and reusable solution for Fine Uploader users that favor golang on the server. Moving it into the FineUploader org potentially increases the popularity of this repo, and users will be able to `go get github.com/FineUploader/go-server`.

I'd love to discuss this further, and really hope this can be part of FineUploader and evolve even further. Thanks for all of your hard work on this.

**Comment by orlandovald** [comment]
I like the idea and definitely interested, let me know the details and how do we proceed with this.

**Comment by rnicholus** [comment]
Here are the steps as I see them (short to long-term):
1. I invite you to the FineUploader organization.
2. You transfer the repo into the FineUploader organization. I would think an appropriate name would be "go-server".
3. I accept the transfer, and the repo is moved into FineUploader
4. I find some cycles in the next week or so to test out the golang server and open up issues based on feedback. The goal is to ensure the server is generic enough such that users can `go get` it and fit it into their environment w/out modifying the code. This is currently how the 2 PHP server repos are setup.
5. After it is apparent that the server is ready for use, we add it to the documentation and reference it as the official server for golang users. 
6. Talk about an S3 version too! (go-s3-server).

**Comment by rnicholus** [comment]
If you have any questions that require longer discussions, I'm usually on freenode. Just click on any of the freenode badges in any FineUploader org repo README (assuming you have an IRC client + a freenode login).

**Comment by orlandovald** [comment]
Sounds good, send me the invite to the fineuploader org and I'll transfer the repo

**Comment by orlandovald** [comment]
I tried to transfer the repo but I get "You don’t have admin rights to FineUploader" error.

**Comment by rnicholus** [comment]
Sorry about that. GitHub permissions are poorly designed and nearly
impossible to understand and assign correctly. I originally assigned you
the correct permission, or so I thought. I'll need to contact github to
resolve this. Please standby for a new invite.

**Comment by rnicholus** [comment]
Looks like GitHub provides no way at all to accept a transfer unless the transfer is coming from a full-owner of the target organization. GitHub permissions have always been well known as poorly designed, but I had no idea, until now, the scope of the issues with their permissions system.

It looks like I will need to temporarily make you a full owner of the entire organization. But first I will need to cleanup the private repos in the org, which contain keys, passwords other private data that I would like to keep private. After the repo has been transferred, I will make you an admin of your golang repo, as well as a member of the fine-uploader repo (if you'd like). I hope to have this all straightened out in the next few days. Sorry for the delay and thanks for your patience.

**Comment by orlandovald** [comment]
Wow, that's going to be a painful process, would it be easier to create a new account so you don't have to go through the cleanup? Then you can transfer it from the temp account to the Fineuploader org maybe? No problem from my side either way.

**Comment by rnicholus** [comment]
Hey, that's a good idea! I'll create a "transfer" organization now & make you an owner. After you transfer the repo into this transfer org, I'll transfer it on to FineUploader and then send you an invite to admin your go repo & member permissions for the fine-uploader repo. Sound good to you?

**Comment by orlandovald** [comment]
Sounds good, go ahead.

**Comment by rnicholus** [comment]
The invitation should be awaiting your approval. Please let me know if you did not receive it.

**Comment by orlandovald** [comment]
Sorry, I missed the email, first move complete :)

**Comment by rnicholus** [comment]
should be a member invite for FineUploader waiting for you now

**Comment by rnicholus** [comment]
Welcome to Fine Uploader! You're the admin of this repo 🙇 . I plan to test out your server a bit more and write up any updates I think will be helpful.

**Comment by orlandovald** [comment]
Thanks Ray.
