### ISSUE TITLE
Update the server languages logo on FineUploader.com to include the golang mascot

### ISSUE THREAD

**Issue by rnicholus** [orlandovald/fineuploader-go-server#3]
Can probably replace the rails logo for now, at least until [this code](http://stackoverflow.com/a/37654230/486979) is turned into a repo.

**Comment by orlandovald** [comment]
Should this issue be transferred to the fineuploader.com repo? 
I know enough **GIMP** to be able to do this, is this the image you are talking about? 
https://github.com/FineUploader/fineuploader.com/blob/gh-pages/img/server-support.png

**Comment by rnicholus** [comment]
Indeed that is the image. I recently moved the website to the FineUploader/fineuploader.com repo. Please open pull request against that repo. Thanks!
